version: "3"
services:
        jk:
                command: bundle exec jekyll serve --watch --incremental --host=0.0.0.0
                image: jekyll
                volumes:
                        - $PWD:/srv/jekyll
                        - $PWD/vendor/bundle:/usr/local/bundle
                ports:
                        - 4000:4000
